let name = "Love Porwal";
let school = "Masai School";
let grade = "A++";
let section = "fw22";
let rollno = "fw22_0927";
let marks_cc = 99;
let marks_dsa = 99;
let marks_js = 99;
console.log("🆁🅴🅿🅾🆁🆃 🅲🅰🆁🅳");
console.log("Name :",name);
console.log("school :", school);
console.log("grade :", grade);
console.log("section : ", section);
console.log("roll no :",rollno);
console.log("marks cc:", marks_cc);
console.log("marks dsa:", marks_dsa);
console.log("marks js:", marks_js);
